baseURL = 'https://nakag916.github.io'
title = 'Fool on the Internet'
languageCode = 'ja'
defaultContentLanguage = "ja"
theme = "Blonde"

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
hasCJKLanguage = true

[params]
# Base color of the website.
# https://tailwindcss.com/docs/background-color
base_color = "bg-gray-800"

# The number of articles to be displayed on a single page.
paginator_pages = "5"

# Number of tags to be displayed.
tagsLimit = 20

# Dark mode by default : dark
# Light mode by default : light
# darkmode = 'dark'
  [params.widgets]
    # Display widgets
    display = true

    # Order of widgets to display
    widgets = ["search", "archive", "category", "tags", "recent"]

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  # [[menu.main]]
  #   identifier = "about"
  #   name = "About"
  #   url = "/about/"
  #   weight = 2

  # [[menu.main]]
  #   identifier = "contact"
  #   name = "Contact"
  #   url = "/contact/"
  #   weight = 3

[taxonomies]
category = "categories"
tag = "tags"
archive = "archives"
