baseURL = "https://nakag916.github.io"
title = "Fool on the Internet"
author = "nakag916"
languageCode = "ja"
defaultContentLanguage = "ja"
theme = "Blonde"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
googleAnalytics = "G-6JWB35KP1C"

# Disqus Comment System
disqusShortname = "nakag916"

[params]
# Base color of the website.
# https://tailwindcss.com/docs/background-color
base_color = "bg-gray-800"

#Site description
description = "Fool on the Internet | Powered by Hugo Theme Blonde"

# The number of articles to be displayed on a single page.
paginator_pages = "5"

# Number of tags to be displayed.
tagsLimit = 20

# Dark mode by default : dark
# Light mode by default : light
# darkmode = "dark"

  [params.widgets]
    # Display widgets
    display = true

    # Order of widgets to display
    widgets = ["search", "archive", "category", "tags", "recent"]

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  # [[menu.main]]
  #   identifier = "about"
  #   name = "About"
  #   url = "/about/"
  #   weight = 2

  # [[menu.main]]
  #   identifier = "contact"
  #   name = "Contact"
  #   url = "/contact/"
  #   weight = 3

  [[menu.main]]
    identifier = "termofservices"
    name = "Term of Services"
    url = "/termofservices/"
    weight = 4


[taxonomies]
category = "categories"
tag = "tags"
archive = "archives"
